//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionNomina.Core
{
    
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BANESCO_DEVEntities : DbContext
    {
        public BANESCO_DEVEntities()
            : base("name=BANESCO_DEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        
        public virtual DbSet<RedACH> RedACHes { get; set; }
        public virtual DbSet<RedLBTR> RedLBTRs { get; set; }
        public virtual DbSet<IndicatorBank> IndicatorBanks { get; set; }
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<TransactionConvert> TransactionConverts { get; set; }
    }
}
