//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionNomina.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedACH
    {
        public int Id { get; set; }
        public string Entidad { get; set; }
        public string RouteAndTransitCheckDigit { get; set; }
        public string Currency { get; set; }
        public string RegUser { get; set; }
        public System.DateTime RegDate { get; set; }
    }
}
